project/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages import views

from account.views import signup, signin, signout, activate, profile, profile_edit, account_edit, settings_edit, profile_list
from quaero.views import site_list, site_pages_list, site_page, search_home, search_result

urlpatterns = [
	# home
	url(r'^$', search_home, name="home"),
	# Quaero
	url(r'^search/$', search_result, name="search-result"),
	url(r'^sites$', site_list, name="site-list"),
	url(r'^pages/(?P<site_url>.*?)$', site_pages_list, name="site-pages-list"),
	url(r'^page/(?P<url>.*?)$', site_page, name="page"),
	# admin
	url(r'^admin/', admin.site.urls, name='admin'),
	# User Accounts
	url(r'^signup/$', signup, name='signup'),
	url(r'^login/$', signin, name='signin'),
	url(r'^logout/$', signout, {'next_page': '/'}, name='signout'),
	url(r'^activate/(?P<activation_key>\w+)/$', activate, name='activate'),
	url(r'^activate/retry/(?P<activation_key>\w+)/$', activate, name='activate_retry'),
	url(r'^activate_success/$', activate, name='activate_success'),
	url(r'^profile/(?P<username>[-\w]+)$', profile, name="profile"),
	url(r'^profile/(?P<username>[-\w]+)/edit-account$', account_edit, name="account_edit"),
	url(r'^profile/(?P<username>[-\w]+)/edit-profile$', profile_edit, name="profile_edit"),
	url(r'^profile/(?P<username>[-\w]+)/edit-settings$', settings_edit, name="user_settings_edit"),
	url(r'^profiles/$', profile_list, name="profile_list"),
	# all the pages
	url(r'^(?P<slug>[-\w]+)$', views.flatpage),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/forms.py
from __future__ import unicode_literals

from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from .models import AccountSignup, Profile
from .settings import REMEMBER_ME_DAYS


USERNAME_RE = r'^[\.\w]+$'
attrs_dict = {'class': 'required'}


class SignupForm(forms.Form):
	"""
	Form for creating a new user account.
	Username must contain only letters, numbers, dots and underscores.
	"""
	username = forms.RegexField(regex=USERNAME_RE, max_length=128, widget=forms.TextInput(attrs=attrs_dict), label=_("Username"),
								error_messages={'invalid': _('Username must contain only letters, numbers, dots and underscores.')})
	email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': _("Email"), 'class': 'required'}), label=_("Email"))
	password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False), label=_("Password"))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False), label=_("Repeat password"))
	tos = forms.BooleanField(widget=forms.CheckboxInput(attrs=attrs_dict),
							 label=_('I have read and agree to the Terms of Service'),
							 error_messages={'required': _('You must agree to the terms to register.')})

	def clean_username(self):
		"""
		Validate that the username is alphanumeric and is not already in use.
		"""
		try:
			user = get_user_model().objects.get(username__iexact=self.cleaned_data['username'])
		except get_user_model().DoesNotExist:
			pass
		else:
			if AccountSignup.objects.filter(user__username__iexact=self.cleaned_data['username']).exclude(activation_key='active'):
				raise forms.ValidationError(_('This username is already taken but not confirmed. Please check your email for verification steps.'))
			raise forms.ValidationError(_('This username is already taken.'))
		return self.cleaned_data['username']

	def clean_email(self):
		""" Validate that the e-mail address is unique. """
		if get_user_model().objects.filter(email__iexact=self.cleaned_data['email']):
			if AccountSignup.objects.filter(user__email__iexact=self.cleaned_data['email']).exclude(activation_key='active'):
				raise forms.ValidationError(_('This email is already in use but not confirmed. Please check your email for verification steps.'))
			raise forms.ValidationError(_('This email is already in use. Please supply a different email.'))
		return self.cleaned_data['email']

	def clean(self):
		"""
		Validates that the values entered into the two password fields match.
		"""
		if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
			if self.cleaned_data['password1'] != self.cleaned_data['password2']:
				raise forms.ValidationError(_('The two password fields didn\'t match.'))
		return self.cleaned_data

	def save(self):
		"""
		Creates a new user and account. Returns the newly created user.
		"""
		username, email, password = (self.cleaned_data['username'],
									 self.cleaned_data['email'],
									 self.cleaned_data['password1'])
		new_user = AccountSignup.objects.create_user(username, email, password,)
		return new_user


class SinginForm(forms.Form):
	"""
	A custom form where the identification can be a e-mail address or username.
	"""
	identification = forms.CharField(label=_("Email or username"),
									widget=forms.TextInput(attrs=attrs_dict),
									max_length=75,
									error_messages={'required': _("Either supply us with your email or username.")})
	password = forms.CharField(label=_("Password"),
								widget=forms.PasswordInput(attrs=attrs_dict, render_value=False))
	remember_me = forms.BooleanField(widget=forms.CheckboxInput(),
									required=False,
									label=_('Remember me for %(days)d days') % {'days': REMEMBER_ME_DAYS})

	def clean(self):
		"""
		Checks for the identification and password.
		If the combination can't be found will raise an invalid sign in error.
		"""
		identification = self.cleaned_data.get('identification')
		password = self.cleaned_data.get('password')

		if identification and password:
			user = authenticate(username=identification, password=password)
			if user is None:
				raise forms.ValidationError(_("Please enter a correct username or email and password. Note that both fields are case-sensitive."))
		return self.cleaned_data


class EditAccountForm(forms.ModelForm):
	"""
	Form for editing user profiles
	"""

	def __init__(self, *args, **kw):
		super(EditAccountForm, self).__init__(*args, **kw)
		self.fields['password'].widget = forms.PasswordInput()
		self.fields['password'].required = False

		self.fields['username'].widget.attrs = {'before_addon': _("fa fa-user"),}
		self.fields['email'].widget.attrs = {'before_addon': _("fa fa-envelope-o"),}
		self.fields['first_name'].widget.attrs = {'before_addon': _("fa fa-user-o"),}
		self.fields['last_name'].widget.attrs = {'before_addon': _("fa fa-user-o"),}
		self.fields['password'].widget.attrs = {'before_addon': _("fa fa-eye-slash "),}

		self.fields.keyOrder = [
			'username',
			'email',
			'first_name',
			'last_name',
			'password',
			]

	class Meta:
		model = User
		fields = ('username', 'email', 'first_name', 'last_name', 'password')

	def clean_username(self):
		username = self.cleaned_data.get('username')
		try:
			user = User.objects.get(username=username)
			if user.pk == self.instance.id:
				return username
		except User.DoesNotExist:
			return username
		raise forms.ValidationError("This user already exist. choose another username!")

	def clean_email(self):
		email = self.cleaned_data.get('email')
		try:
			user = User.objects.get(email=email)
			if user.pk == self.instance.id:
				return email
		except User.DoesNotExist:
			return email
		raise forms.ValidationError('This email address is already in use. Please supply a different email address.')

	def clean_password(self):
		password = self.cleaned_data.get('password')
		if 8 > len(password) > 0:
			raise forms.ValidationError('This Password is too short. it must be at least 8 characters.')
		else:
			return password

	def save(self, commit=True):
		# Ignore Password field in this form
		EditAccountForm.Meta.fields = tuple(x for x in EditAccountForm.Meta.fields if x != 'password')
		user = super(EditAccountForm, self).save(commit=False)
		user.username = self.cleaned_data['username']
		user.email = self.cleaned_data['email']
		if self.cleaned_data['password'] and len(self.cleaned_data['password']):
			user.set_password(self.cleaned_data['password'])
		if commit:
			user.save()
		return user


class EditProfileForm(forms.ModelForm):
	"""
	Form for editing user profiles
	"""
	class Meta:
		model = Profile
		fields = ('avatar_option', 'avatar', 'website', 'bio', 'language', 'country',\
			'location', 'gender', 'public_mail')


class EditSettingsForm(forms.ModelForm):
	"""
	Form for editing user settings
	"""
	class Meta:
		model = Profile
		fields = ('privacy', 'notification_setting')

account/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

from .forms import SignupForm, SinginForm, EditProfileForm, EditAccountForm, EditSettingsForm
from .settings import REMEMBER_ME_DAYS, LOGIN_REDIRECT_URL
from .models import AccountSignup, Profile


def profile_list(request):
	users = User.objects.all()

	page = request.GET.get('page', 1)
	paginator = Paginator(users, 20)
	adjacent_pages = 5
	page = int(page)
	start_page = max(page - adjacent_pages, 1)
	if start_page <= 3: start_page = 1
	end_page = page + adjacent_pages + 1
	if end_page >= paginator.num_pages - 1: end_page = page + 1
	try:
		users = paginator.page(page)
	except PageNotAnInteger:
		users = paginator.page(1)
	except EmptyPage:
		users = paginator.page(paginator.num_pages)

	context = {
		'users': users,
		'paginator_range': range(start_page, end_page),
	}
	return render(request, "profile-list.html", context)


def profile(request, username):
	user = User.objects.get(username=username)
	user_profile = Profile.objects.get(user=user)

	if request.user.is_superuser is not True and user_profile.privacy == 'p': # private
		return render(request, "profile-private.html")

	context = {
		'user': user,
		'username': username,
		'profile': user_profile,
	}
	return render(request, "profile.html", context)


def account_edit(request, username):
	"""
	Account Form
	"""
	if request.user.is_superuser is not True and request.user.username != username :
		return render(request, "profile-no-permission.html")

	user = User.objects.get(username=username)
	user_profile = Profile.objects.get(user=user)
	form = EditAccountForm(instance=user)

	if request.method == 'POST':
		form = EditAccountForm(request.POST, request.FILES, instance=user)
		if form.is_valid():
			form.save()
			return redirect('profile', username=user.username)
	context = {
		'user': user,
		'profile': user_profile,
		'form': form,
	}
	return render(request, "profile-account-edit.html", context)


def profile_edit(request, username):
	"""
	Profile Form
	"""
	if request.user.is_superuser is not True and request.user.username != username :
		return render(request, "profile-no-permission.html")

	user = User.objects.get(username=username)
	user_profile = Profile.objects.get(user=user)
	form = EditProfileForm(instance=user_profile)

	if request.method == 'POST':
		form = EditProfileForm(request.POST, request.FILES, instance=user_profile)
		if form.is_valid():
			form.save()
	context = {
		'user': user,
		'profile': user_profile,
		'form': form,
	}
	return render(request, "profile-edit.html", context)


def settings_edit(request, username):
	"""
	Edit account settings
	"""
	if request.user.is_superuser is not True and request.user.username != username :
		return render(request, "profile-no-permission.html")

	user = User.objects.get(username=username)
	user_profile = Profile.objects.get(user=user)
	form = EditSettingsForm(instance=user_profile)

	if request.method == 'POST':
		form = EditSettingsForm(request.POST, request.FILES, instance=user_profile)
		if form.is_valid():
			form.save()
	context = {
		'user': user,
		'profile': user_profile,
		'form': form,
	}
	return render(request, "profile-settings-edit.html", context)


def signup(request):
	"""
	Signup of an account.
	1. Signup with username, email and password
	2. get confirmation email with an activation link
	3. redirect user to homepage or visiting page
	"""
	form = SignupForm()
	if request.method == 'POST':
		form = SignupForm(request.POST, request.FILES)
		if form.is_valid():
			user = form.save()
			redirect_url = '/'
			return redirect(redirect_url)

	context = {
		'form': form,
	}
	return render(request, "signup-form.html", context)


def signin(request):
	"""
	login of an account.
	1. Signup with (username or email) and password
	2. redirect
	"""
	form = SinginForm()
	if request.method == 'POST':
		form = SinginForm(request.POST, request.FILES)
		if form.is_valid():
			identification, password, remember_me = (form.cleaned_data['identification'],
													 form.cleaned_data['password'],
													 form.cleaned_data['remember_me'])
			user = authenticate(username=identification,
								password=password)
			if user.is_active:
				if 'next' in request.GET:
					if request.GET['next']:
						redirect_url = request.GET['next']
					else:
						redirect_url = LOGIN_REDIRECT_URL
				else:
					referer = request.META.get('HTTP_REFERER', '').rstrip('/')
					if referer and not referer.endswith('login'):
						redirect_url = referer
					else:
						redirect_url = '/'
				login(request, user)
				if remember_me:
					request.session.set_expiry(REMEMBER_ME_DAYS * 86400)
				else:
					request.session.set_expiry(0)

				# Whereto now?
				return HttpResponseRedirect(redirect_url)
			else:
				# TODO: add message to show user that he is inactive
				return redirect(LOGIN_REDIRECT_URL)

	context = {
		'form': form,
	}
	return render(request, "signin-form.html", context)


def signout(request, next_page):
	"""
	Signs out the user
	"""
	logout(request)
	request.session.flush()
	referer = request.META.get('HTTP_REFERER', '').rstrip('/')
	if not next_page:
		if referer and not referer.endswith('login'):
			redirect_url = referer
		else:
			redirect_url = '/'
		return HttpResponseRedirect(redirect_url)
	else:
		return HttpResponseRedirect(next_page)


def activate(request, activation_key):
	"""
	Activate a user with an activation key.

	The key is a SHA1 string. When the SHA1 is found with an
	:class:`AccountSignup`, the :class:`User` of that account will be activated.
	After a successful activation the view will redirect to ``success_url``.
	If the SHA1 is not found, the user will be shown the ``failed_url`` template displaying a fail message.
	If the SHA1 is found but expired, ``retry_template`` is used instead so user can get a new activation key.
	"""
	try:
		if not AccountSignup.objects.check_expired_activation(activation_key):
			user = AccountSignup.objects.activate_user(activation_key)
			if user:
				# Sign the user in.
				User = get_user_model()
				this_user = User.objects.get(email__iexact=user.email)
				this_user.backend = 'django.contrib.auth.backends.ModelBackend'
				login(request, user=this_user)
				redirect_to = reverse('profile', kwargs={'username': user.username})
				return redirect(redirect_to)
			else:
				return render(request, "activate_fail.html")
		else:
			context = {
				'activation_key': activation_key,
			}
			return render(request, "activate_retry.html", context)

	except AccountSignup.DoesNotExist:
		return render(request, "activate_fail.html")


def activate_retry(request, activation_key):
	"""
	Reissue a new ``activation_key`` for the user with the expired ``activation_key``.
	"""
	try:
		if AccountSignup.objects.check_expired_activation(activation_key):
			new_key = AccountSignup.objects.reissue_activation(activation_key)
			if new_key:
				return render(request, "activate_retry_success.html")
			else:
				return redirect(reverse('activate', args=(activation_key,)))
		else:
			return redirect(reverse('activate', args=(activation_key,)))
	except AccountSignup.DoesNotExist:
		return redirect(reverse('activate', args=(activation_key,)))

account/templates/activate_fail.html
{% extends "base-clean-header.html" %}
{% load static %}
{% load thumbnail %}
{% load i18n %}

{% block title %}{% trans "Account activation failed." %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account could not be activated..." %}</h2>{% endblock %}

{% block content %}
<main class="container activation-page">
	<p>{% trans "Your account could not be activated. This could be because your activation link has aged." %}</p>
	<p>{% trans "Please try signing up again or contact us if you think something went wrong." %}</p>
</main>
{% endblock %}

account/templates/activate_retry.html
{% extends "base-clean-header.html" %}
{% load static %}
{% load thumbnail %}
{% load i18n %}

{% block title %}{% trans "Account activation failed." %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account could not be activated..." %}</h2>{% endblock %}

{% block content %}
<main class="container activation-page">
	<p>{% trans "Your account could not be activated because activation link is expired." %}</p>
	<p><a href="{% url 'activate_retry' activation_key %}">{% trans "Request a new activation link." %}</a></p>
</main>
{% endblock %}

account/templates/activate_retry_success.html
{% extends "base-clean-header.html" %}
{% load static %}
{% load thumbnail %}
{% load i18n %}

{% block title %}{% trans "Account re-activation succeeded." %}{% endblock %}
{% block content_title %}<h2>{% trans "Account re-activation" %}</h2>{% endblock %}

{% block content %}
<main class="container activation-page">
	<p>{% blocktrans %}You requested a new activation of your account..{% endblocktrans %}</p>
	<p>{% blocktrans %}You have been sent an e-mail with an activation link to the supplied email.{% endblocktrans %}</p>
</main>
{% endblock %}

account/templates/profile-account-edit.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}

{% block header %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{% trans "Edit Account" %}{% endblock %}

{% block content %}
<main class="container profile">
    <div class="row">
		<div class="col-md-3 profile-sidebar-container">
			{% include "profile-sidebar.html" %}
		</div>
		<div class="col-md-9">
			<div class="row profile-body">
				<div class="content clearfix">
					<form action="" enctype="multipart/form-data" method="post">
						{% csrf_token %}
						{{ form.non_field_errors }}
						{% for field in form %}
							{{ field.label_tag }}
							{% if field.field.widget.attrs.before_addon %}
								<div class="form-group input-group">
									<span class="input-group-addon"><i class="{{ field.field.widget.attrs.before_addon }}"></i></span>
									{% render_field field placeholder=field.label class+="form-control input-lg" %}
								</div>
							{% else %}
								<div class="form-group">
								{% render_field field placeholder=field.label class+="form-control input-lg" %}
								</div>
							{% endif %}
							{{ field.errors }}
						{% endfor %}
						<input class="btn btn-primary pull-right" value="{% trans 'Save changes' %}" type="submit">
					</form>
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock %}

account/templates/profile-edit.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}

{% block header %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{% trans "Edit Profile" %}{% endblock %}

{% block content %}
<main class="container profile">
    <div class="row">
		<div class="col-md-3 profile-sidebar-container">
			{% include "profile-sidebar.html" %}
		</div>
		<div class="col-md-9">
			<div class="row profile-body">
				<div class="content clearfix">
					<form action="" enctype="multipart/form-data" method="post">
						{% csrf_token %}
						{{ form.non_field_errors }}
						{% for field in form %}
							{{ field.label_tag }}
							{% if field.field.widget.attrs.before_addon %}
								<div class="form-group input-group">
									<span class="input-group-addon"><i class="{{ field.field.widget.attrs.before_addon }}"></i></span>
									{% render_field field placeholder=field.label class+="form-control input-lg" %}
								</div>
							{% else %}
								<div class="form-group">
									{% render_field field placeholder=field.label class+="form-control input-lg" %}
								</div>
							{% endif %}
							{{ field.errors }}
						{% endfor %}
						<input class="btn btn-primary pull-right" value="{% trans 'Save changes' %}" type="submit">
					</form>
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock %}

account/templates/profile-list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}
{% load i18n %}

{% block content %}
<ul id="profile_list">
  {% for profile in profile_list %}
  <li>
  <a href="{% url 'profile' profile.user.username %}"><img src="{{ profile.get_mugshot_url }}" /></a>
  <a href="{% url 'profile' profile.user.username %}">{{ profile.user.username }}</a>
  </li>
  {% endfor %}
</ul>

{% if is_paginated %}
<div class="pagination">
  <span class="step-links">
	{% if page_obj.has_previous %}
	<a href="{% url 'profile_list_paginated' page_obj.previous_page_number %}">{% trans 'previous' %}</a>
	{% endif %}

	<span class="current">
	  {% blocktrans with page_obj.number as page and page_obj.paginator.num_pages as num_pages %}
	  Page {{ page }} of {{ num_pages }}
	  {% endblocktrans %}
	</span>

	{% if page_obj.has_next %}
	<a href="{% url 'profile_list_paginated'  page_obj.next_page_number %}">{% trans 'next' %}</a>
	{% endif %}
  </span>
</div>
{% endif %}

{% endblock %}

account/templates/profile-no-permission.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load i18n %}

{% block header %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{% trans "Edit Profile" %}{% endblock %}

{% block content %}
<main class="container-box">
    <div class="content clearfix">
		<h2 class="text-capitalize">
			Private Profile
		</h2>
		<p>Sorry, this profile is made private by it's owner. you can't view it.
		</p>
	</div>
</main>
{% endblock %}

account/templates/profile-private.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load i18n %}

{% block header %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{% trans "Edit Profile" %}{% endblock %}

{% block content %}
<main class="container-box">
    <div class="content clearfix">
		<h2 class="text-capitalize">
			Private Profile
		</h2>
		<p>Sorry, this profile is made private by it's owner. you can't view it.
		</p>
	</div>
</main>
{% endblock %}

account/templates/profile-settings-edit.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}

{% block header %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{% trans "Edit Account" %}{% endblock %}

{% block content %}
<main class="container profile">
    <div class="row">
		<div class="col-md-3 profile-sidebar-container">
			{% include "profile-sidebar.html" %}
		</div>
		<div class="col-md-9">
			<div class="row profile-body">
				<div class="content clearfix">
					<form action="" enctype="multipart/form-data" method="post">
						{% csrf_token %}
						{{ form.non_field_errors }}
						{% for field in form %}
							{% if field.field.widget.attrs.before_addon %}
								<div class="form-group input-group">
									<span class="input-group-addon"><i class="{{ field.field.widget.attrs.before_addon }}"></i></span>
									{% render_field field placeholder=field.label class+="form-control input-lg" %}
								</div>
							{% else %}
								<div class="form-group">
								{% render_field field placeholder=field.label class+="form-control input-lg" %}
								</div>
							{% endif %}
							{{ field.errors }}
						{% endfor %}
						<input class="btn btn-primary pull-right" value="{% trans 'Save changes' %}" type="submit">
					</form>
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock %}

account/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block header %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{{ profile.user.username }} - {% trans "Profile" %}{% endblock %}
{% block content %}
<main class="container profile">
    <div class="row">
		<div class="col-md-3 profile-sidebar-container">
			{% include "profile-sidebar.html" %}
		</div>
		<div class="col-md-9">
			<div class="row profile-body">
				<div class="profile-fields">
					{% if profile.bio %}
					<div class="profile-bio">
						{{ profile.bio|linebreaks }}
					</div>
					{% endif %}
					{% if profile.location %}
					<div class="profile-location">
						<i class="fa fa-map-marker"></i>
						{{ profile.location }}
					</div>
					{% endif %}
					{% if profile.website %}
					<div class="profile-location">
						<i class="fa fa-external-link-square"></i>
						{{ profile.website|urlize }}
					</div>
					{% endif %}
					{% if profile.public_mail %}
					<div class="profile-public-mail">
						<i class="fa fa-envelope"></i>
						{{ profile.public_mail }}
					</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock %}

account/templates/signin-form.html
{% extends "base-clean-header.html" %}
{% load static %}
{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}

{% block header %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{% trans "Login" %}{% endblock %}

{% block content %}
<div class="container-box">
	<div class="container">
		<div class="text-center">
            <a class="navbar-brand" href="{% url 'home' %}">Project</a>
        </div>
		<div class="content clearfix">
			<form action="" method="post">
				{% csrf_token %}
				<fieldset>
					<h2>Signin</h2>
					<hr class="colorgraph">
					{{ form.non_field_errors }}
					{% for field in form %}
						{% if not field.name == 'remember_me' %}
							<div class="form-group">
							{% render_field field placeholder=field.label class+="form-control input-lg" %}
							</div>
							{{ field.errors }}
						{% endif %}
					{% endfor %}
				</fieldset>
				<hr class="colorgraph">
				<div class="clearfix">
					{{ form.remember_me.errors }}
				</div>
				<span class="pull-left checkbox form-checkbox-container">
					<label for="id_remember_me">{{ form.remember_me }} {{ form.remember_me.label }}</label>
				</span>
				<input type="submit" value="SignIn" class="btn btn-lg btn-primary pull-right" />
			</form>
		</div>
		<div class="container-open">
			Don't have an account? <a href="{% url 'signup' %}">Create Account</a>
		</div>
	</div>
</div>
{% endblock %}

account/templates/signup-form.html
{% extends "base-clean-header.html" %}
{% load static %}
{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}

{% block header %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{% trans "SignUp" %}{% endblock %}

{% block content %}
<div class="container-box">
	<div class="container">
		<div class="text-center">
            <a class="navbar-brand" href="{% url 'home' %}">Project</a>
        </div>
		<div class="content clearfix">
			<form action="" method="post">
				{% csrf_token %}
				<fieldset>
					<h2>Signup</h2>
					<hr class="colorgraph">
					{{ form.non_field_errors }}
					{% for field in form %}
						{# Displaying checkboxes differently #}
						{% if not field.name == 'tos' %}
							<div class="form-group">
							{% render_field field placeholder=field.label class+="form-control input-lg" %}
							</div>
							{{ field.errors }}
						{% endif %}
					{% endfor %}
				</fieldset>
				<hr class="colorgraph">
				<div class="clearfix">
					{{ form.tos.errors }}
				</div>
				<span class="half pull-left checkbox form-checkbox-container">
					<label for="id_tos">{{ form.tos }} {{ form.tos.label }}</label>
				</span>
				<input type="submit" value="SignUp" class="btn btn-lg btn-primary pull-right" />
			</form>
		</div>
		<div class="container-open">
			Already have an account? <a href="{% url 'signin' %}">Login to your account</a>
		</div>
	</div>
</div>

{% endblock %}